[project]
name = "servane-site"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask-flatpages==0.8.3",
    "frozen-flask==1.0.2",
    "pytz>=2025.2",
]
